# Generated by Django 2.2 on 2019-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email *')),
                ('name', models.CharField(max_length=200, verbose_name='Ονοματεπώνυμο *')),
                ('phone_number', models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο')),
                ('message', models.TextField(verbose_name='Μήνυμα *')),
            ],
        ),
    ]
