# Generated by Django 2.2.4 on 2021-04-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['is_readed', '-timestamp']},
        ),
    ]
