# Generated by Django 2.2 on 2019-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Από..')),
                ('date_end', models.DateField(blank=True, help_text='Αν μείνει κενό διαρκεί για πάντα', null=True, verbose_name='Ημερομηνία Μέχρι..')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Τίτλος')),
                ('discount_type', models.CharField(choices=[('a', 'Ποσοστό'), ('b', 'Ποσό'), ('c', 'Ακριβές Ποσό')], max_length=1, verbose_name='Έιδος Έκπτωσης')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Αξία')),
                ('products_related', models.ManyToManyField(to='catalogue.Product')),
            ],
        ),
    ]
