# Generated by Django 2.2 on 2019-09-12 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('a', 'Πελατης Λιανικης'), ('b', 'Πελατης Eshop')], default='a', max_length=1)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Όνομα')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Επίθετο')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση Αποστολής')),
                ('shipping_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Πόλη')),
                ('shipping_zip_code', models.IntegerField(blank=True, null=True, verbose_name='Τκ')),
                ('billing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip_code', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο')),
                ('phone1', models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο 1')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Κινητό')),
                ('fax', models.CharField(blank=True, max_length=10, verbose_name='Fax')),
                ('is_retail', models.BooleanField(default=True)),
                ('is_eshop', models.BooleanField(default=True)),
                ('vat', models.CharField(blank=True, max_length=9, verbose_name='ΑΦΜ')),
                ('vat_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Εφορία')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Off the record Manual Balance', max_digits=20, verbose_name='Επιπλέον Αξία')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Υπόλοιπο')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='catalogue.Product')),
                ('profile_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='accounts.Profile')),
            ],
        ),
    ]
