# Generated by Django 2.2 on 2019-10-04 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_auto_20190920_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 10, 4), verbose_name='Ημερομηνία'),
        ),
    ]
