# Generated by Django 2.2.6 on 2019-11-04 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20191004_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2019, 11, 4), verbose_name='Ημερομηνία'),
        ),
    ]
