# Generated by Django 2.2.6 on 2020-02-18 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20200217_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 2, 18), verbose_name='Ημερομηνία'),
        ),
    ]
