# Generated by Django 2.2.6 on 2020-02-21 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_auto_20200220_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 2, 21), verbose_name='Ημερομηνία'),
        ),
    ]
