# Generated by Django 2.2.4 on 2020-09-20 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0010_auto_20200304_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.date(2020, 9, 20), verbose_name='Ημερομηνία'),
        ),
    ]
