# Generated by Django 2.2.6 on 2019-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_different_color_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['ordering_by_letter', '-active', '-id'], 'verbose_name_plural': '1. Products'},
        ),
        migrations.AddField(
            model_name='characteristics',
            name='ordering_by_letter',
            field=models.CharField(default='c', max_length=15),
        ),
        migrations.AddField(
            model_name='characteristicsvalue',
            name='ordering_by_letter',
            field=models.CharField(default='c', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering_by_letter',
            field=models.CharField(default='c', max_length=15),
        ),
    ]
