# Generated by Django 2.2.6 on 2020-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20200217_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='eng_title',
            field=models.CharField(max_length=250, null=True, verbose_name='Τιτλος'),
        ),
    ]
