# Generated by Django 2.2.6 on 2020-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_color_eng_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='eng_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Τιτλος στη Αγγλικη Εκδοση'),
        ),
        migrations.AddField(
            model_name='characteristicsvalue',
            name='eng_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Τιτλος στη Αγγλικη Εκδοση'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='eng_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Τιτλος στη Αγγλικη Εκδοση'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Εμφανιση στο Site'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Τίτλος στην Ελληνικη'),
        ),
        migrations.AlterField(
            model_name='characteristicsvalue',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Εμφανιση στο Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Εμφανιση στο Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Τιτλος'),
        ),
    ]
