# Generated by Django 2.2.6 on 2020-02-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20200217_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='eng_title',
        ),
    ]
