# Generated by Django 2.2.6 on 2020-02-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_remove_productcharacteristics_eng_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='eng_title',
            field=models.CharField(max_length=250, null=True, verbose_name='Τιτλος για την Αγγλικη Εκδοση'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Τιτλος'),
        ),
    ]
