# Generated by Django 2.2 on 2020-03-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20200221_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '3. Κατηγορίες Site'},
        ),
    ]
