# Generated by Django 2.2.6 on 2019-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20191004_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('a', 'Μεγάλο Banner --> (1970*718)'), ('b', 'Μεσαίο Banner --> No Use. For future'), ('c', 'Μικρό Banner -->(600*250)')], default='a', max_length=1),
        ),
    ]
