# Generated by Django 2.2.6 on 2020-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20200217_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='eng_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='eng_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
