# Generated by Django 2.2.6 on 2020-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20200218_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='eng_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Τιτλος στη Αγγλικη Εκδοση'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='eng_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Τιτλος στη Αγγλικη Εκδοση'),
        ),
    ]
