# Generated by Django 2.2 on 2020-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20200219_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='site_tracker',
            field=models.URLField(blank=True, null=True),
        ),
    ]
