# Generated by Django 2.2.4 on 2021-04-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_shipping_site_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='instagram_photos/')),
            ],
        ),
    ]
