# Generated by Django 2.2 on 2019-09-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ονομα')),
                ('last_name', models.CharField(max_length=100, verbose_name='Επιθετο')),
                ('address', models.CharField(max_length=100, verbose_name='Διευθυνση')),
                ('city', models.CharField(max_length=100, verbose_name='Πολη')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Ταχυδρομικος Κωδικας')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Κινητό')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Σταθερο Τηλεφωνο')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειωσεις')),
                ('cart_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_profile', to='cart.Cart')),
            ],
        ),
    ]
