# Generated by Django 2.2 on 2019-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Διευθυνση'),
        ),
        migrations.AlterField(
            model_name='cartprofile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Κινητό'),
        ),
        migrations.AlterField(
            model_name='cartprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Πολη'),
        ),
        migrations.AlterField(
            model_name='cartprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ονομα'),
        ),
        migrations.AlterField(
            model_name='cartprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επιθετο'),
        ),
        migrations.AlterField(
            model_name='cartprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ταχυδρομικος Κωδικας'),
        ),
    ]
