# Generated by Django 2.2 on 2019-09-12 13:50

import chartsize.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατασταση')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Ονομασια')),
                ('image', models.ImageField(upload_to=chartsize.models.upload_photo)),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Brand')),
                ('products', models.ManyToManyField(blank=True, to='catalogue.Product')),
            ],
        ),
    ]
